general:
  input_file: "search/input/tower.json"
  output_folder: "search/output/"
  k: 5

ucts:
  max_iter: 40000
  max_iter_per_node: 5
  max_edge_len: 4
  grid_density_unit: 1
  num_neighbors: 3
  clamp_tolerance: 1
