general:
  input_file: "input/bridge_hanging_round.json"
  output_folder: "output/"
  k: 5

ucts:
  max_iter: 5000
  max_iter_per_node: 3
  max_edge_len: 3
  grid_density_unit: 1.2
  num_neighbors: 6
  clamp_tolerance: 0.1
