general:
  input_file: "input/tower.json"
  output_folder: "output/"
  image_folder: "images/"
  k: 10

ucts:
  max_nodes: 7
  max_iter: 100
  max_iter_per_node: 10
  coordinate_range:
    - - 0.0
      - 2.0
    - - 0.0
      - 2.0
    - - 0.0
      - 4.0
  grid_density_unit: 1.2
  num_neighbors: 6
  clamp_tolerance: 0.1
truss_env:
  E: 1.93e+11
  pho: 8.0e+3
  sigma_T: 123.0e+6
  sigma_C: 123.0e+6
  slenderness_ratio_c: 180.0
  slenderness_ratio_t: 220.0
  dislimit: 0.002
