general:
  input_file: "input/tower.json"
  output_folder: "output/"
  image_folder: "images/"
  k: 10

ucts:
  max_nodes: 7
  max_iter: 5000
  max_iter_per_node: 3
  max_edge_len: 3
  coordinate_range:
    - - 0.0
      - 2.0
    - - 0.0
      - 2.0
    - - 0.0
      - 4.0
  grid_density_unit: 1.2
  num_neighbors: 6
  clamp_tolerance: 0.1
