general:
  input_file: "input/tower.json"
  output_folder: "output/"
  k: 5

ucts:
  max_iter: 5000
  max_iter_per_node: 3
  max_edge_len: 4
  grid_density_unit: 1
  num_neighbors: 3
  clamp_tolerance: 1
